name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    
    - name: Build, tag, and push docker image to Amazon ECR Public
      run: |
        docker build -t webapp .
        docker tag webapp:latest public.ecr.aws/a4h1f3t0/webapp:latest
        docker push public.ecr.aws/a4h1f3t0/webapp:latest
      
      
